= Hawkular Data mining Forecast

Lightweight library for time series modeling and forecasting.

=== Time series models
 - Simple exponential smoothing
 - Double exponential smoothing (Holt's linear trend)
 - Seasonal triple exponential smoothing (Holt Winters)
 - Simple moving average (Weighted moving average)

All variants of exponential smoothing contains optimizer which selects best smoothing parameters for given time series.
Optimizers minimizes mean square error of one step ahead forecasts using non linear optimization algorithm
(Nelder-Mead simplex).

AutomaticForecaster can be used for the best model selecting. It selects best based on Akaike information criterion (AIC
and AICc) or Bayesian information criterion (BIC). If the time series changes AutomaticForecaster can select
different model than previously selected, therefore it can be used on arbitrary time series stream data.

=== Time series manipulation & Statistics
 - Augmented Dickey-Fuller test
 - Autocorrelation function (ACF)
 - Time series decomposition
 - Time series lagging
 - Time series differencing
 - Automatic period identification

=== Dependencies
 - Apache commons math
 - Apache commons lang3
 - Guava

