## Alert prediction ##

Project is being developed for Red Hat and supervised by link:https://github.com/Jiri-Kremser[Jiri Kremser].
In the future it will be probably integrated into link:http://www.hawkular.org/[Hawkular].

== Buil & Run

To build Hawkular Data mining, clone this repository and build from the top level.

[source,shell]
----
$ git clone https://github.com/hawkular/hawkular.git
$ cd hawkular-datamining
$ mvn clean install -Pdev
$ start hawkular
$ hawkular-datamining-dist/target/wildfly-9.0.0.Final/bin/standalone.sh --debug 9797 -Djboss.socket.binding.port-offset=1000
----

### Description in English ###
TODO

### Description in Czech ###
Student za pomoci metod strojového učeni pro časové rady nebo za pomoci regresní
analýzy vyvine modul, který na základe historických dat umožní včasnou detekci
blížících se události. Tyto události jsou předem definovaný jako takzvaný
výstrahy (alerts) většinou jako konjunkce či disjunkce jednoduchých podmínek
vztahujících se k datum z časových řad.

Data jsou charakteru <časové razítko, hodnota>, navíc je možno zjistit metadata
jako jednotky, název, zda je to veličina, která jen roste, atd. Jedná se
zpravidla o naměřená data, například místo na disku, volná paměť, atd.

Součástí teoretické části práce by mělo být srovnáni metod pro dolováni v
časových řadách a také vypořádáni se s tzv. concept drift, či detekcemi
cykličnosti v datech. Vybraný algoritmus bude poté implementován v jazyce Java a
modul bude v případe dobrých výsledku začleněn do monitorovacího systému
Hawkular, toto vyžaduje, aby byl modul šířen také pod svobodnou licenci, a to
Apache Licence 2.0.

### Documentation
Latex documentation can be generated by running `make` in `doc` directory.

### Additional information & Links
* link:https://docs.google.com/document/d/127rSiX4ElhGC4QNYK7OJiz0uufGbRprELlvfevLOuXI/edit?usp=sharing[Google Doc]
* link:http://www.hawkular.org/[Hawkular]
