= Hawkular Data mining

Project is being developed for Red Hat and supervised by link:https://github.com/Jiri-Kremser[Jiri Kremser].
In the future it will be probably integrated into link:http://www.hawkular.org/[Hawkular].

ifdef::env-github[]
[link=https://travis-ci.org/hawkular/hawkular-datamining]
image:https://travis-ci.org/hawkular/hawkular-datamining.svg?branch=master["Build Status", link="https://travis-ci.org/hawkular/hawkular-datamining"]{nbsp}

endif::[]

== Build & Run

To build Hawkular Data mining, clone this repository and build from the top level. Then build link:https://github.com/hawkular/hawkular/tree/datamining[Hawkular] branch datamining and run server

[source,shell]
----
# build Hawkular Datamining
$ git clone https://github.com/hawkular/hawkular-datamining.git
$ cd hawkular-datamining
$ mvn install
# build Hawkular with deployed datamining
$ git clone -b datamining git@github.com:hawkular/hawkular.git
$ cd hawkular
$ mvn install -Pdev
# run Hawkular
$ dist/target/hawkular-*/bin/standalone.sh

----

== Enable prediction in Hawkular
To enable forecasting of metrics create Relationship from Tenant to Metric, MetricType or Tenant.

Following example enables forecasting for all metrics under given tenant.
----
$ tenant=$(curl -s GET 'http://jdoe:password@localhost:8080/hawkular/inventory/tenant'| grep --color=never -oP 'path" : "\K/t;[0-9a-z\-]+')
$ curl -ivX POST -H "Content-Type: application/json" 'http://jdoe:password@localhost:8080/hawkular/inventory/tenants/relationships' -d '{
    "name": "__inPrediction",
    "source": "'$tenant'",
    "target": "'$tenant'",
    "properties": {"forecastingHorizon": 150}
}'
----
Source and target are canonical paths.

.Source
* Tenant

.Target
* Tenant - predict all tenant's metrics, lover levels overrides prediction interval
* MetricType - predict metric of given type
* Metric

== Description in English
==== Alert prediction in metric data based on time series analysis
Student by application of time series analysis will develop a module which will
predict future events based on continuously incoming and historical time series data.
This events are defined as alerts usually as a conjunction or a disjunction of
simple clauses based on data from time series.

Each data point is a tuple consisting of timestamp and value. There are also available
metadata such as name, units, type of quantity defining if it is a monotonic
function or a non-monotonic. These metric data are for instance result of the
measurement of free disk space, free memory, Java heap usage etc.

Theoretical part should incorporate comparison of time series data
mining methods and deal with problems as a concept drift and an anomaly detection.
Chosen algorithm will be implemented in Java language and the module in case
of good results will be merged into monitoring system Hawkular. This requires
that module will be distributed under Apache Licence 2.0.

== Description in Czech
==== Predikce události v metrických datech za pomoci analýzy časových řad
Student za pomoci analýzy časových řad vyvine modul, který na základě příchozích
a historických dat umožní včasnou detekci blížících se událostí. Tyto události
jsou předem definovány jako takzvané výstrahy (alerts), většinou jako konjunkce
či disjunkce jednoduchých podmínek vztahujících se k datům z časových řad.

Data jsou charakteru <časové razítko, hodnota>, navíc je možno zjistit metadata
jako jednotky, název, zda je to veličina, která jen roste, atd. Jedná se
zpravidla o naměřená data, například místo na disku, volná paměť, atd.

Součástí teoretické části práce by mělo být srovnání metod pro dolováni v
časových řadách a také vypořádání se s tzv. concept drift, či detekcemi
cykličnosti v datech. Vybraný algoritmus bude poté implementován v jazyce Java a
modul bude v případě dobrých výsledku začleněn do monitorovacího systému
Hawkular, toto vyžaduje, aby byl modul šířen také pod svobodnou licenci, a to
Apache Licence 2.0.

== Documentation

Latex documentation can be generated by running `make` in `doc` directory.

== Additional information & Links

* link:https://docs.google.com/document/d/127rSiX4ElhGC4QNYK7OJiz0uufGbRprELlvfevLOuXI/edit?usp=sharing[Google Doc]
* link:http://www.hawkular.org/[Hawkular]

== License

Hawkular-Inventory is released under Apache License, Version 2.0 as described in the link:LICENSE[LICENSE] document

----
   Copyright 2015 Red Hat, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
----

During build if you are getting `Some files do not have the expected license header` just run `mvn license:format`.
